######################################################################
# Automatically generated by qmake (2.00a) lör mar 19 19:53:25 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
#qt	+= sql
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
